### ISSUE TITLE
Link the root URL to the GitHub repo

### ISSUE THREAD

**Issue by j-f1** [ArtOfCode-/desktop-stack-serv#1]
Currently, https://auth.artofcode.co.uk is a 404. It should link to this repo.

**Comment by ArtOfCode-** [comment]
Will require the base framework to be refactored a bunch: ArtOfCode-/nails#1

**Comment by ArtOfCode-** [comment]
ArtOfCode-/nails#1 is complete, and so is this (467d5b4a357a584ddf408a15dbfcb84153fddcd7).
